# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jevon/programs/emulators/nes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jevon/programs/emulators/nes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.22.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jevon/programs/emulators/nes/CMakeFiles /Users/jevon/programs/emulators/nes//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jevon/programs/emulators/nes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nes

# Build rule for target.
nes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nes
.PHONY : nes

# fast build rule for target.
nes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nes.dir/build.make CMakeFiles/nes.dir/build
.PHONY : nes/fast

#=============================================================================
# Target rules for targets named test_instructions

# Build rule for target.
test_instructions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_instructions
.PHONY : test_instructions

# fast build rule for target.
test_instructions/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/build
.PHONY : test_instructions/fast

#=============================================================================
# Target rules for targets named test_utils

# Build rule for target.
test_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_utils
.PHONY : test_utils

# fast build rule for target.
test_utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/build
.PHONY : test_utils/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/build/main.o: src/build/main.c.o
.PHONY : src/build/main.o

# target to build an object file
src/build/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nes.dir/build.make CMakeFiles/nes.dir/src/build/main.c.o
.PHONY : src/build/main.c.o

src/build/main.i: src/build/main.c.i
.PHONY : src/build/main.i

# target to preprocess a source file
src/build/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nes.dir/build.make CMakeFiles/nes.dir/src/build/main.c.i
.PHONY : src/build/main.c.i

src/build/main.s: src/build/main.c.s
.PHONY : src/build/main.s

# target to generate assembly for a file
src/build/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nes.dir/build.make CMakeFiles/nes.dir/src/build/main.c.s
.PHONY : src/build/main.c.s

src/cpu/cpu.o: src/cpu/cpu.c.o
.PHONY : src/cpu/cpu.o

# target to build an object file
src/cpu/cpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/cpu.c.o
.PHONY : src/cpu/cpu.c.o

src/cpu/cpu.i: src/cpu/cpu.c.i
.PHONY : src/cpu/cpu.i

# target to preprocess a source file
src/cpu/cpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/cpu.c.i
.PHONY : src/cpu/cpu.c.i

src/cpu/cpu.s: src/cpu/cpu.c.s
.PHONY : src/cpu/cpu.s

# target to generate assembly for a file
src/cpu/cpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/cpu.c.s
.PHONY : src/cpu/cpu.c.s

src/cpu/instruction_set.o: src/cpu/instruction_set.c.o
.PHONY : src/cpu/instruction_set.o

# target to build an object file
src/cpu/instruction_set.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/instruction_set.c.o
.PHONY : src/cpu/instruction_set.c.o

src/cpu/instruction_set.i: src/cpu/instruction_set.c.i
.PHONY : src/cpu/instruction_set.i

# target to preprocess a source file
src/cpu/instruction_set.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/instruction_set.c.i
.PHONY : src/cpu/instruction_set.c.i

src/cpu/instruction_set.s: src/cpu/instruction_set.c.s
.PHONY : src/cpu/instruction_set.s

# target to generate assembly for a file
src/cpu/instruction_set.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/instruction_set.c.s
.PHONY : src/cpu/instruction_set.c.s

src/cpu/test/test.o: src/cpu/test/test.cpp.o
.PHONY : src/cpu/test/test.o

# target to build an object file
src/cpu/test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/test/test.cpp.o
.PHONY : src/cpu/test/test.cpp.o

src/cpu/test/test.i: src/cpu/test/test.cpp.i
.PHONY : src/cpu/test/test.i

# target to preprocess a source file
src/cpu/test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/test/test.cpp.i
.PHONY : src/cpu/test/test.cpp.i

src/cpu/test/test.s: src/cpu/test/test.cpp.s
.PHONY : src/cpu/test/test.s

# target to generate assembly for a file
src/cpu/test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/cpu/test/test.cpp.s
.PHONY : src/cpu/test/test.cpp.s

src/mem/mem.o: src/mem/mem.c.o
.PHONY : src/mem/mem.o

# target to build an object file
src/mem/mem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/mem/mem.c.o
.PHONY : src/mem/mem.c.o

src/mem/mem.i: src/mem/mem.c.i
.PHONY : src/mem/mem.i

# target to preprocess a source file
src/mem/mem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/mem/mem.c.i
.PHONY : src/mem/mem.c.i

src/mem/mem.s: src/mem/mem.c.s
.PHONY : src/mem/mem.s

# target to generate assembly for a file
src/mem/mem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_instructions.dir/build.make CMakeFiles/test_instructions.dir/src/mem/mem.c.s
.PHONY : src/mem/mem.c.s

src/utils/test/test.o: src/utils/test/test.cpp.o
.PHONY : src/utils/test/test.o

# target to build an object file
src/utils/test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils/test/test.cpp.o
.PHONY : src/utils/test/test.cpp.o

src/utils/test/test.i: src/utils/test/test.cpp.i
.PHONY : src/utils/test/test.i

# target to preprocess a source file
src/utils/test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils/test/test.cpp.i
.PHONY : src/utils/test/test.cpp.i

src/utils/test/test.s: src/utils/test/test.cpp.s
.PHONY : src/utils/test/test.s

# target to generate assembly for a file
src/utils/test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils/test/test.cpp.s
.PHONY : src/utils/test/test.cpp.s

src/utils/utils.o: src/utils/utils.c.o
.PHONY : src/utils/utils.o

# target to build an object file
src/utils/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils/utils.c.o
.PHONY : src/utils/utils.c.o

src/utils/utils.i: src/utils/utils.c.i
.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils/utils.c.i
.PHONY : src/utils/utils.c.i

src/utils/utils.s: src/utils/utils.c.s
.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils/utils.c.s
.PHONY : src/utils/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... nes"
	@echo "... test_instructions"
	@echo "... test_utils"
	@echo "... src/build/main.o"
	@echo "... src/build/main.i"
	@echo "... src/build/main.s"
	@echo "... src/cpu/cpu.o"
	@echo "... src/cpu/cpu.i"
	@echo "... src/cpu/cpu.s"
	@echo "... src/cpu/instruction_set.o"
	@echo "... src/cpu/instruction_set.i"
	@echo "... src/cpu/instruction_set.s"
	@echo "... src/cpu/test/test.o"
	@echo "... src/cpu/test/test.i"
	@echo "... src/cpu/test/test.s"
	@echo "... src/mem/mem.o"
	@echo "... src/mem/mem.i"
	@echo "... src/mem/mem.s"
	@echo "... src/utils/test/test.o"
	@echo "... src/utils/test/test.i"
	@echo "... src/utils/test/test.s"
	@echo "... src/utils/utils.o"
	@echo "... src/utils/utils.i"
	@echo "... src/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

